#!/bin/bash

HOOK=.git/hooks/pre-push

# check if script is already there
if [ -e $HOOK ]; then
    echo "Already set up!"
    exit 0
fi

# install black
python3 -m pip install black

# write script in .git/hooks
printf "#!/bin/bash\n\npython3 -m black --config pyproject.toml ." > $HOOK
# make it executable
chmod +x $HOOK
